# Generated by Django 4.1.3 on 2023-01-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0002_alter_product_options_product_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='limited',
            field=models.BooleanField(default=False, verbose_name='Ограниченная серия'),
        ),
    ]
