# Generated by Django 4.1.3 on 2023-01-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0003_alter_product_limited'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
        ),
        migrations.AlterModelOptions(
            name='imageproduct',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='propertyproduct',
            options={'verbose_name': 'Характеристики', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='миниатюры'),
        ),
        migrations.RemoveField(
            model_name='propertyproduct',
            name='device',
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(through='app_catalog.PropertyProduct', to='app_catalog.titleproperty'),
        ),
        migrations.AddField(
            model_name='propertyproduct',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app_catalog.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyproduct',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_catalog.titleproperty'),
        ),
    ]
