# Generated by Django 4.1.3 on 2023-01-16 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0005_alter_titleproperty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyproduct',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app_catalog.product', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='propertyproduct',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_catalog.titleproperty', verbose_name='Заголовок'),
        ),
    ]
