# Generated by Django 4.1.3 on 2023-01-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_configurations', '0001_initial'),
        ('app_catalog', '0007_alter_titleproperty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_configurations.category'),
            preserve_default=False,
        ),
    ]
