# Generated by Django 4.1.3 on 2023-01-18 15:47

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_configurations', '0011_alter_sitesettings_min_cost_for_free_delivery_and_more'),
        ('app_catalog', '0008_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='app_configurations.category'),
        ),
    ]
