# Generated by Django 4.1.3 on 2023-02-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0011_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
            },
        ),
        migrations.CreateModel(
            name='ExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extradata', to='app_catalog.product', verbose_name='Устройство')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extradata', to='app_catalog.titledata', verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Дополнительные данные',
                'verbose_name_plural': 'Сведения',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='extra_data',
            field=models.ManyToManyField(through='app_catalog.ExtraData', to='app_catalog.titledata', verbose_name='Дополнительные данные'),
        ),
    ]
