# Generated by Django 4.1.3 on 2023-02-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0012_titledata_extradata_product_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
            },
        ),
        migrations.AlterModelOptions(
            name='titledata',
            options={'verbose_name': 'Наименование', 'verbose_name_plural': 'Наименования'},
        ),
        migrations.AlterField(
            model_name='extradata',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extradata', to='app_catalog.valuedata', verbose_name='Значение'),
        ),
    ]
