# Generated by Django 4.1.3 on 2023-01-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movement_goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='content',
            new_name='cart',
        ),
    ]
