# Generated by Django 4.1.3 on 2023-02-04 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_movement_goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Чья корзина'),
        ),
        migrations.AddField(
            model_name='ordercontents',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_movement_goods.order'),
        ),
        migrations.AddField(
            model_name='ordercontents',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app_products.product', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='Чей заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='structure',
            field=models.ManyToManyField(related_name='order', through='app_movement_goods.OrderContents', to='app_products.product', verbose_name='Содержание заказа'),
        ),
        migrations.AddField(
            model_name='insidecart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.product', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='insidecart',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app_movement_goods.usercart'),
        ),
    ]
