# Generated by Django 4.1.3 on 2023-01-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movement_goods', '0003_alter_usercart_options_usercart_session_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insidecart',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
