# Generated by Django 4.1.3 on 2023-01-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movement_goods', '0004_alter_insidecart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='session',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Сессия'),
        ),
    ]
