# Generated by Django 4.1.3 on 2023-01-25 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_movement_goods', '0005_alter_usercart_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Чья корзина'),
        ),
    ]
