# Generated by Django 4.1.3 on 2023-01-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movement_goods', '0006_alter_usercart_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insidecart',
            old_name='goods',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='usercart',
            name='session',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Сессия'),
        ),
    ]
