# Generated by Django 4.1.3 on 2023-01-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movement_goods', '0009_order_ordercontents_order_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercontents',
            options={'verbose_name': 'Содержание', 'verbose_name_plural': 'Составы'},
        ),
    ]
