# Generated by Django 4.1.3 on 2023-02-04 23:14

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='url категории')),
                ('icon', models.FileField(blank=True, upload_to='category/', verbose_name='Иконка')),
                ('exec_picture', models.ImageField(blank=True, upload_to='category/', verbose_name='Изображение')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app_configurations.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_usual_delivery', models.DecimalField(decimal_places=2, help_text='Цена обычной доставки', max_digits=10, verbose_name='обычная')),
                ('cost_express_delivery', models.DecimalField(decimal_places=2, help_text='Цена экспресс доставки', max_digits=10, verbose_name='экспресс')),
                ('min_cost_for_free_delivery', models.DecimalField(decimal_places=2, help_text='Минимальная сумма для бесплатной доставки', max_digits=10, verbose_name='Минимум')),
                ('quantity_top_product', models.PositiveIntegerField(default=8, help_text='Количество популярных товаров на главной станице', verbose_name='Популярные товаров')),
                ('time_cache_data', models.PositiveIntegerField(default=1, help_text='Кеш хранения данных о товаре в днях', verbose_name='Время кэша данных')),
                ('category_main_page', models.ManyToManyField(blank=True, db_table='app_configurations_category_main_page', default='', help_text='Надо выбирать не более 3-х', to='app_configurations.category', verbose_name='Категории главной страницы')),
                ('root_category', models.ForeignKey(blank=True, help_text='Начальная категория выпадающего меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_category', to='app_configurations.category', verbose_name='Корень каталога')),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурации',
            },
        ),
    ]
