# Generated by Django 4.1.3 on 2023-01-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_configurations', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Конфигурация', 'verbose_name_plural': 'Конфигурации'},
        ),
    ]
