# Generated by Django 4.1.3 on 2023-01-17 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_configurations', '0003_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='edge_for_free_delivery',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бесплатный порог'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='quantity_popular',
            field=models.PositiveIntegerField(default=8, verbose_name='Количество популярных товаров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='root_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_category', to='app_configurations.category', verbose_name='Корень каталога'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='time_cache_product',
            field=models.PositiveIntegerField(default=1, verbose_name='Время кэша данных'),
        ),
    ]
