# Generated by Django 4.1.3 on 2023-01-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_configurations', '0005_alter_sitesettings_cost_express_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='cost_express',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='edge_for_free_delivery',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='quantity_popular',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='time_cache_product',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cost_express_delivery',
            field=models.DecimalField(decimal_places=2, default=500, help_text='Цена экспресс доставки', max_digits=10, verbose_name='экспресс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_cost_for_free_delivery',
            field=models.DecimalField(decimal_places=2, default=20000, help_text='Минимальная стоимость бесплатной доставки', max_digits=10, verbose_name='Минимальная стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quantity_top_product',
            field=models.PositiveIntegerField(default=8, help_text='Количество топ-товаров', verbose_name='Популярные товаров'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='time_cache_data',
            field=models.PositiveIntegerField(default=1, help_text='Кеш данных о товаре', verbose_name='Время кэша данных'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cost_usual_delivery',
            field=models.DecimalField(decimal_places=2, help_text='Цена обычной доставки', max_digits=10, verbose_name='обычная'),
        ),
    ]
