# Generated by Django 4.1.3 on 2023-01-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_configurations', '0007_alter_sitesettings_category_main_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='min_cost_for_free_delivery',
            field=models.DecimalField(decimal_places=2, help_text='Минимальная стоимость бесплатной доставки', max_digits=10, verbose_name='Минимум'),
        ),
    ]
