# Generated by Django 4.1.3 on 2023-01-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_configurations', '0010_alter_sitesettings_category_main_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='min_cost_for_free_delivery',
            field=models.DecimalField(decimal_places=2, help_text='Минимальная сумма для бесплатной доставки', max_digits=10, verbose_name='Минимум'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='quantity_top_product',
            field=models.PositiveIntegerField(default=8, help_text='Количество популярных товаров на главной станице', verbose_name='Популярные товаров'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='root_category',
            field=models.ForeignKey(blank=True, help_text='Начальная категория выпадающего меню', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_category', to='app_configurations.category', verbose_name='Корень каталога'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='time_cache_data',
            field=models.PositiveIntegerField(default=1, help_text='Кеш хранения данных о товаре в днях', verbose_name='Время кэша данных'),
        ),
    ]
