# Generated by Django 4.1.3 on 2023-02-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='отзыв')),
                ('pub_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('edit_at', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('hide_on', models.BooleanField(default=False, verbose_name='Скрытый')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы о товарах',
            },
        ),
        migrations.CreateModel(
            name='ProxyProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Товар с отзывом',
                'verbose_name_plural': 'Товары с отзывами',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_products.product',),
        ),
    ]
