# Generated by Django 4.1.3 on 2023-02-03 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_catalog', '0013_valuedata_alter_titledata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Товар с отзывом',
                'verbose_name_plural': 'Товары с отзывами',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_catalog.product',),
        ),
        migrations.CreateModel(
            name='CommentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300, verbose_name='отзыв')),
                ('pub_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('edit_at', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('hide_on', models.BooleanField(default=False, verbose_name='Скрыт')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
