# Generated by Django 4.1.3 on 2023-02-04 23:14

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Дополнительные данные',
                'verbose_name_plural': 'Сведения',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_device', models.CharField(default='', max_length=50, verbose_name='Тип устройства')),
                ('fabricator', models.CharField(default='', max_length=100, verbose_name='Производитель')),
                ('model', models.CharField(default='', max_length=100, verbose_name='Модель')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL товара')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='В наличии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('available', models.BooleanField(default=True, verbose_name='В продаже')),
                ('limited', models.BooleanField(default=False, verbose_name='Ограниченная серия')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='app_configurations.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='TitleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Наименование',
                'verbose_name_plural': 'Наименования',
            },
        ),
        migrations.CreateModel(
            name='TitleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
            },
        ),
        migrations.CreateModel(
            name='ValueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
            },
        ),
        migrations.CreateModel(
            name='PropertyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение характеристики')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app_products.product', verbose_name='Устройство')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.titleproperty', verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Характеристики',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='extra_data',
            field=models.ManyToManyField(through='app_products.ExtraData', to='app_products.titledata', verbose_name='Дополнительные данные'),
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(through='app_products.PropertyProduct', to='app_products.titleproperty'),
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='миниатюры')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_products.product')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='extradata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extradata', to='app_products.product', verbose_name='Устройство'),
        ),
        migrations.AddField(
            model_name='extradata',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extradata', to='app_products.titledata', verbose_name='Параметр'),
        ),
        migrations.AddField(
            model_name='extradata',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extradata', to='app_products.valuedata', verbose_name='Значение'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('slug',)},
        ),
    ]
